# Generated by Django 5.0.2 on 2024-02-26 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_aboutus_alter_news_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='ФИО')),
                ('desc', models.TextField(verbose_name='отзывы')),
            ],
            options={
                'verbose_name_plural': 'отзывы',
            },
        ),
    ]
